### ISSUE TITLE
[Feature Request] Hide parts of settings when they're currently unused

### ISSUE THREAD

**Issue by NutchapolSal** [hako-mikan/sd-webui-regional-prompter#130]
I seem to keep deactivating the extension, then after some time write prompts that uses the extension features without actually activating the extension

#### Examples
- the main "Active" checkbox should hide or show all of the options
- "Divide mode" radio buttons should show their relevant settings
  - "Horizontal" or "Vertical" shows "Divide Ratio", "visualize and make Template" show when "Horizontal" or "Vertical" is selected
  - "Mask" shows the mask drawing canvas, canvas settings, etc
  - etc.
- "Use base prompt" should show/hide "Base Ratio"
- etc.

**Comment by Symbiomatrix** [comment]
The clutter has been on my mind for some time, since we introduced mask and prompt modes. Though it does have visiblity properties, I don't know whether gradio supports change events for all components, and it's likely not a great solution; I'd rather use tabs like webui for the modes, but only if I can send the current tab as input somehow.
