### ISSUE TITLE
Unable to get 4 horizontal regions to work.

### ISSUE THREAD

**Issue by Cross22** [hako-mikan/sd-webui-regional-prompter#154]
As a test case I tried to recreate this painting: https://en.wikipedia.org/wiki/The_Singing_Butler
No matter what settings I try; I can only get the 2 people in the center to appear; it's like the left and right regions are being ignored.

Regional Prompter:
Active = On, 
Mode: Attention, 
Use Common Prompt: On, 
Split: Horizontal, 
Divide Ration: 1,1,1,1

EulerA, 30 steps, 7 CFG, 768 x 512

Positive:
high resolution, detailed  ADDCOMM
standing maid ADDCOL
couple dancing tango in the sand, red gown ADDCOL
couple dancing tango in the sand,  black tuxedo ADDCOL
standing butler

**Comment by Symbiomatrix** [comment]
All checkpoints I know have a tendency to generate subjects in the center due to their training data. Prompt control applies to the content, not the basis; if your prompt were just "standing butler" or "standing maid", they would appear in the center, would they not?
You must either add something to the extent of "4 people" in your common, or, since the target image is somewhat asymmetrical, use controlnet openpose to force them into existence (possibly with that image itself).

**Comment by hako-mikan** [comment]
For example, the top image uses a base prompt `7-girls`, but it is not highly successful.
The probability of getting anything other than seven is higher.
The extension specifies a prompt for each area, but that area is treated as part of the whole, not a single picture, so you should use something like 4person, as @Symbiomatrix mentioned.
