### ISSUE TITLE
Unable to use latent mode for separating loras, getting attribute error

### ISSUE THREAD

**Issue by disastrouscash** [hako-mikan/sd-webui-regional-prompter#17]
Enabling the latent mode causes a callback error for me. Disabling it removes the error but prevents the lora separation.

Example prompt:
masterpiece, digital art, best quality, public park, BREAK
GirlA standing, wearing blue summer dress,lora:LoraOfGirlA_Str06TriggerGirlA:0.6 BREAK
GirlB standing, wearing red summer dress lora:LoraOfGirlBStr04-1TriggerGirlB:0.4

The created image seems split during the creation process to two halves, but usually relents to just 1girl being rendered, sometimes 2nd half of the picture renders as a blur.
![example](https://user-images.githubusercontent.com/127510631/228647634-fc659b11-b2ac-4513-b324-d13d21ebbbcf.jpg)

File "C:\stable-diffusion\gpu\stable-diffusion-webui-directml\modules\script_callbacks.py", line 161, in cfg_denoiser_callback
c.callback(params)
File "C:\stable-diffusion\gpu\stable-diffusion-webui-directml\extensions\sd-webui-regional-prompter\scripts\rp.py", line 666, in denoiser_callback
ct = params.text_cond.clone()
AttributeError: 'CFGDenoiserParams' object has no attribute 'text_cond'

**Comment by Symbiomatrix** [comment]
I'm unfamiliar with this "directml" version of webui, but is it possible you have a stale version of it? Supposedly, a CFGDenoiserParams class should contain the text_cond attribute since march 11 (see commit history at https://github.com/AUTOMATIC1111/stable-diffusion-webui/commits/master/modules/script_callbacks.py).
I'm working with last month's version of webui, haven't had time to upgrade, so temporarily patched this by adding just the CFGDenoised classes to script_callbacks (as proposed in latent couple's issues), and ignoring the text_cond parms. It works, technically, but I suspect it isn't quite as intended from the results I've gotten.
I'd first recommend upgrading webui if that's the case for you, otherwise this patch to rp along with CFGDenoised should suffice.

```
rp.py
    def denoiser_callback(self, params: CFGDenoiserParams):
        if lactive:
            xt = params.x.clone()
            ict = params.image_cond.clone()
            st =  params.sigma.clone()
            # SBM TEMP Stale version matching.
            if hasattr(params,"text_cond"):
                ct =  params.text_cond.clone()
            areas = xt.shape[0] // self.batch_size -1

            for a in range(areas):
                for b in range(self.batch_size):
                    params.x[b+a*self.batch_size] = xt[a + b * areas]
                    params.image_cond[b+a*self.batch_size] = ict[a + b * areas]
                    params.sigma[b+a*self.batch_size] = st[a + b * areas]
                    if hasattr(params,"text_cond"): # SBM TEMP Stale version matching.
                        params.text_cond[b+a*self.batch_size] = ct[a + b * areas]
```

**Comment by disastrouscash** [comment]
Oh my god, I previously had git pull in my webui-user.bat to ensure I'm always at the latest version, but after having to troubleshoot problems with inpainting that arose, so as it seems when I removed all extra commands from the .bat I never remembered to restore the git pull command after figuring out the problem. So yes, my version was behind and it was the cause -.-
My apologies and thanks for the help.

**Comment by Symbiomatrix** [comment]
Great. If you want, let us know how well the lora separation worked for you.
