### ISSUE TITLE
Generating more than one character consistently across multiple images with Regional Prompter?

### ISSUE THREAD

**Issue by anirudhv** [hako-mikan/sd-webui-regional-prompter#185]
I've been using the Regional Prompter extension on Stable Diffusion with the AUTOMATIC1111 web UI.

The regional prompter is great for generating multiple characters in one image. Without the regional prompter, stable diffusion may generate one person with characteristics/features of all the characters described in the prompt. If multiple people are generated, they may be having a mix of each other's characteristics.

I am not sure how to maintain character consistency across multiple images, though.

Let's say there are four characters -

1. A 10 year old boy (the son)

2.  A 12 year old girl (the daughter)

3. A man in his early 40s (the father)

4. A woman in her early 40s (the mother)

Let's say I want the first image to be the boy (1) and the girl (2) holding hands and walking home from school with backpacks on their back.

The second image should be the parents (3)(4) standing by the door waving at the children.

The third image should be the boy (1) washing his hands in the sink.

The fourth image should be the girl (2) washing her hands in the sink.

The fifth image should be the entire family eating ice cream at the dining table.

The sixth image should the man (3) and the boy (1) reading a book together on the sofa.

How should I craft the prompts so that all four characters look exactly the same (or extremely similar) in all the images they are in? I know the seed number needs to be the same, but I am having a hard time crafting the right prompt.

Any help would be appreciated. Thanks!

![image](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/19772331/090b70f5-6358-4ff1-aafb-af738f79b883)
These are my regional prompter settings btw, and I am willing to change them to fit the needs of the image I want.

**Comment by hako-mikan** [comment]
That's a very challenging question. I get the impression that you're thinking about creating a manga or story. At this point, it's extremely difficult. This is due to the nature of stable diffusion itself. Let's take a boy dressed in a red T-shirt and blue shorts as an example. It's very hard to maintain the same outfit and appearance for this boy while changing the specified scene. Even if you specify outdoors and indoors, even with the same seed, the outfit is likely to subtly differ. Even colors like red and blue may vary. It may not be a problem in terms of the face, as some models may only generate the same face, but when it comes to clothing, age, or physique, it's very difficult to maintain consistency across different scenes. You could use LoRA to a certain extent to fix the appearance of the boy. However, there are limitations.

Indeed, this extension can produce various characters at the same time, but considering your usage, it would be good to also look into LoRA and control nets.

**Comment by anirudhv** [comment]
@hako-mikan Thanks for the reply. Yes, I am creating an AI children's storybook generator. Users enter a story prompt and AI generates both the story text and pictures.

I understand that 100% identical characters is not possible. What matters is that the readers of the story can easily acknowledge that the characters are the same across multiple images despite their differences. If a few colors are incorrect, that is fine, too. I will try to use something like Visual Chat GPT to fix those minor issues. 

I will look into LoRA and control nets and try out more prompts with regional prompter, too. I will also see if another image generation model like Dall-E is better for what I am trying to accomplish. (Sadly, there is no midjourney API).

**Comment by hako-mikan** [comment]
I wish you good results. Good luck!
