### ISSUE TITLE
Extension not appearing in the WebUI

### ISSUE THREAD

**Issue by xrxlkool** [hako-mikan/sd-webui-regional-prompter#20]
I've tried installing the regional prompter via the extensions tab in the WebUI and by directly placing the rp.py file directly in the stable-diffusion-webui\scripts file path, but haven't been able to get the accordion menu to appear in the WebUI at all. 

Could anyone assist here?

![Screenshot 2023-03-31 091317](https://user-images.githubusercontent.com/116837693/229144863-7a7be21b-0653-4667-99a9-7e1b0ec880b1.png)

**Comment by xrxlkool** [comment]
Guess I never noticed this before; any tips as to how to resolve this?
![image](https://user-images.githubusercontent.com/116837693/229207994-ef49fb48-1954-45fe-9b25-4a58f725e17f.png)

**Comment by Symbiomatrix** [comment]
Is it possible you have a very old version of webui? The one I've set aside, from back before 2/2.1 came out, lacks this import. There has been some major code restructuring in the repo since.
If you want to make sure, open webui (in emu/ai);
1) Go to modules/processing.py: Does it contain the line "import modules.paths as paths" ?
2) Go to modules/paths.py: Does it contain the line "data_path = cmd_opts_pre.data_dir" (or any "data_path") ?

Ps: Putting all your files under downloads is usually not a good idea.

(On a side note, should probably import paths directly rather than from another module which imports it.)

**Comment by hako-mikan** [comment]
Thanks! Fixed.
