### ISSUE TITLE
Lora slowdown.

### ISSUE THREAD

**Issue by Symbiomatrix** [hako-mikan/sd-webui-regional-prompter#21]
Hello @hako-mikan , I saw your recent comment:
Have you been able to pinpoint which webui commit is at fault / since when it started? How noticeable is it (say, a linear / sublinear factor of regions)?

**Comment by hako-mikan** [comment]
The problem has been identified.
https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/80b26d2a69617b75d2d01c1e6b7d11445815ed4d
The method of applying LoRA has changed here. Instead of applying LoRA on every read, it is now applied all the time and rebuilt when there is a change. This rebuilding takes time. When using region-specific LoRA, the rebuild is performed each time the region is switched, which results in slower time. Switching regions must be done every 1 step. I thought about applying the old method, but this update changes the first step of loading LoRA from cuda to cpu, so I may have to switch the entire LoRA module.

**Comment by Symbiomatrix** [comment]
Thanks.
Oof, overhead at every step is pretty bad. I'll try to see if some improvisation comes to mind.

**Comment by hako-mikan** [comment]
I could use the old loading method by changing the LoRA device loaded on the cpu to cuda. But it is unstable because at the moment I don't know how to reset the weights of the model.
If I generate it without LoRA it will be reset, but I don't know where this reset is done.

Latent mode ->normal generation -> Latent mode

The first and last results are different when generated in this order. 
This is because the weights are not reset properly during normal generation. I hope this can be resolved.

**Comment by hako-mikan** [comment]
test version
https://github.com/hako-mikan/sd-webui-regional-prompter/blob/ver5/scripts/rp.py

**Comment by hako-mikan** [comment]
Resolved. I think I forgot to reset the text encoder.
