### ISSUE TITLE
Only 3 of 64 tries worked / Colab notebook Automatic 1111

### ISSUE THREAD

**Issue by MajorGruberth** [hako-mikan/sd-webui-regional-prompter#211]
Today I tried the first time regional prompter and it worked only in 1% of the tries:
Prompt: A man BREAK a woman
Active; Attention; Horizontal; 1,1
Height: 512, width: 768, sampling steps: 25, Euler A, dreamshaper_8 model

--------------
Fun fact: most of the prompts are working, horizontally and vertically, except I put in a second characters (man, woman). Than it just ignores one of the two...

Anything I am doing wrong?

**Comment by hako-mikan** [comment]
In this case, you should enter

`two person, a man BREAK two person, a woman`

In terms of the approach, you would first input the overall picture. In this case, since two individuals are involved, "two persons" would be necessary. Without this, you would likely only get a single individual. After that, you consider the prompts for the left and right sides. In this case, they would be "a man" and "a woman."

**Comment by MajorGruberth** [comment]
ok - I'll try, thanks
