### ISSUE TITLE
Attention mode is not working with multiple people in prompt in different regions since a December update

### ISSUE THREAD

**Issue by lucadreamz** [hako-mikan/sd-webui-regional-prompter#287]
Please advise how to revert to an older version.

I have disabled all other extensions and the problem persists.

**Comment by cassiebug23** [comment]
same problem here, prompts are mixing together, and latent mode causes horrific artifacts in the images when using mutiple loras, never had this issue before recently.

**Comment by rabbitflyer** [comment]
You can revert by going into the extension's directory `.../sd-webui-regional-prompter/` and entering `git checkout HEAD~1`. This will take you back by one commit. Replace `HEAD~1` with the hash of a specific commit if you want to revert to a specific commit. To go back to the current version, enter `git checkout main`.

I've tried reverting back to mid-October's version and the problem persists. Perhaps it's caused by an interaction with an update to A1111 itself? I'll see what I can find.

**Comment by lucadreamz** [comment]
I attempted to revert A1111 itself as well and it didn't work.  Though I'm wondering if it truly reverts everything with A1111 when you do that or if it keeps some settings from the latest version.

**Comment by blugail** [comment]
If anyone actually reverts and gets it working, could they please post the steps? I hate to see this extension die like this.

**Comment by hako-mikan** [comment]
There is no way for me to address the issue based solely on the information provided. 
I can't do anything unless you specify what prompts you are entering and under what conditions this error occurs.

**Comment by rabbitflyer** [comment]
I just checked this and it seems to be working now, at least for me.
