### ISSUE TITLE
This work was plagiarized! Please fight for your right!

### ISSUE THREAD

**Issue by mad-max-4** [hako-mikan/sd-webui-regional-prompter#309]
Hi Hako, 
I must remind you that your wonderful work has been plagiarized by @YangLing0818, and he even wrote a paper and published it on arXiv. Here is the paper link: https://arxiv.org/abs/2401.11708. Worse, he did not cite this repository. Now his paper has been cited 11 times.
You can check his code (https://github.com/YangLing0818/RPG-DiffusionMaster), which is totally same with this repository.  @YangLing0818 argues that the proposed "Compositional Diffusion Generation" is different from your "regional prompter", but all people know that it is just a feeble excuse (see [issue#8](https://github.com/YangLing0818/RPG-DiffusionMaster/issues/8) and [issue#24](https://github.com/YangLing0818/RPG-DiffusionMaster/issues/24)). 
Such behavior will never be tolerated. Please fight for your right!

**Comment by YangLing0818** [comment]
Thanks for your comments. Our RPG **does not have to set up the regions / parameters manually**. More importantly, our diffusion paradigm is a broader concept because we also use it to conduct image editing based on the **MLLM-planned complementary contours**. For better understanding, you can refer to the image editing part in our paper. And we also acknowledge their contributions along with other impressive works in our repo.

**Comment by arcusmaximus** [comment]
It's also worth pointing out that Regional Prompter is licensed under the GPL. This means the author explicitly allows others to take the code and use it in their own project, with some conditions (e.g. the other project must also be open source, which RPG is).

That being said, the GPL requires that derivative works use the same license, while the RPG repository appears to have no license at all.

**Comment by hako-mikan** [comment]
I'm not in this field either, but as a researcher, I was a bit surprised that something like this was done without any citations.
I can't tell if this is common sense for researchers in information science. 
Still, I laughed when I saw an image created from my sample prompt in the paper. 
In this case, I'm not inclined to assert my rights strongly because the idea of the Regional Prompter wasn't mine but someone else's suggestion. 
I just wrote the code for Web-UI. (Though it was quite a struggle.) 
For now, it seems there's no issue since they appear to be citing appropriately. 
The rest is up to the paper's reviewers to make the right decision.

**Comment by hako-mikan** [comment]
Thanks for trying to protect my rights.

**Comment by mad-max-4** [comment]
> I'm not in this field either, but as a researcher, I was a bit surprised that something like this was done without any citations. I can't tell if this is common sense for researchers in information science. Still, I laughed when I saw an image created from my sample prompt in the paper. In this case, I'm not inclined to assert my rights strongly because the idea of the Regional Prompter wasn't mine but someone else's suggestion. I just wrote the code for Web-UI. (Though it was quite a struggle.) For now, it seems there's no issue since they appear to be citing appropriately. The rest is up to the paper's reviewers to make the right decision.

First, copying work from other researcher and pretending it to be their own is definitely **NOT** a common sense in the computer vision community.
Second, they did not cite your work in their paper (I think they submit it to ICML 2024). They just cited your work in their github repo, which is **just a remedy after their submission**.

I really appreciate your generosity, but I think their behavior will definitely have a bad effect on the entire community. Once this paper gets accepted in the future, then some immoral researchers will continue to steal open-source works from github. So I disagree with @arcusmaximus. It's not about the license. It's about the academic ethics.

Anyway, I respect your decision. TBF, I don't think such paper will be accepted by ICML.
