### ISSUE TITLE
Localising loras.

### ISSUE THREAD

**Issue by Symbiomatrix** [hako-mikan/sd-webui-regional-prompter#4]
Loras often have an effect which applies to the whole image; sometimes they offer keywords which can localise the effect, sometimes there are no keywords. This is not always desirable.
Is it possible to make loras apply only to the prompt region wherein they are defined?

**Comment by Symbiomatrix** [comment]
Would it not be possible by hacking the lora multiplier regionally so that lora_forward ignores it? Or does it go deeper than that?

**Comment by hako-mikan** [comment]
Thanks for the advice!! You have inspired me. I may be able to implement it.

**Comment by Symbiomatrix** [comment]
Happy to help, best of luck.

**Comment by Symbiomatrix** [comment]
Did you have any luck with that direction?

**Comment by hako-mikan** [comment]
I have been experimenting with this issue, and it seems that in order to separate LoRA, it must be calculated multiple times throughout the entire U-Net. 
Therefore, it is easier to use the conventional Latent method than the Attention method, so I plan to implement the Latent method first. In the test phase, I was able to separate the LoRAs cleanly, and I expect to be able to release it to the public within a few days. Of course, I will continue to think about Attention method.

**Comment by Symbiomatrix** [comment]
Brilliant. Looking forward to it. The latent extension seems all but dead so it'd be great if regional could take over.
