### ISSUE TITLE
Using LORA and increasing the batch count only applies to the first picture

### ISSUE THREAD

**Issue by freebag668** [hako-mikan/sd-webui-regional-prompter#81]
<html>
<body>

674f40ba (Sun Apr 30 06:01:08 2023) | latest
-- | --

</body>
</html>

https://civitai.com/models/6679
https://civitai.com/models/6362
Using LORA

https://anonfiles.com/16ycueo3zb/20230430_txt
debug TXT ifle

https://postimg.cc/gallery/HgKtwfs
Using 2 LORA (Latent mode)
Batch count 4
Resulting Picture

2lora is applied to the first photo, but not to the other three.
Can this be fixed?

Thanks for all your hard work

**Comment by Symbiomatrix** [comment]
Latent's changed some since the reformat. I haven't debugged, but would venture a guess that possibly, the lora renaming technique with a random identifier is inaccurate because the random seed is the same for all batches, thus skipping over the remainder.,

**Comment by hako-mikan** [comment]
Fixed.

@Symbiomatrix 
There seems to have been a problem with the prompt handled by `lora_namer`, which was called in the second batch. This is because there was an `ADDCOL `or something in the place where the `AND `separator should normally be. This prompt was rewritten in the first `postprocess_image`.

I believe `lora_namer `should be called every batch. The reason is to deal with the fact that the dynamic prompt changes prompt every batch. This was a problem once with the LoRA Block Weight extension.

**Comment by Symbiomatrix** [comment]
I think I see what you mean. But if it rebuild the prompt every batch, wouldn't that mean we'd have to move the whole region construction code to process_batch? Would that even suffice?

**Comment by hako-mikan** [comment]
I don't think it's necessary to deal with modification that destroys the structure of region specification.

**Comment by freebag668** [comment]
https://postimg.cc/gallery/dw0TT2G
Resolved
I am so happy
Thank you!

**Comment by Symbiomatrix** [comment]
Alright then.

Always a pleasure, bud.
