### ISSUE TITLE
Am I doing something wrong using this extension

### ISSUE THREAD

**Issue by Shangooriginal** [hako-mikan/sd-webui-regional-prompter#95]
2D Region Method
Just started using this extension with hopes it help with better composition. However, I've noticed that extension seems to only work for one model for me (anime based), doesn't work for any other anime models or realistic models. Also, I've found only one sampler DPM++ SDE Karras that produce anything near what is written as prompts + special separators (i.e. ADDROW, etc). Sometimes, it is a hit or miss adhering to the prompts too.

With BREAK Method
Managed to get 3 of my favourite anime models to work with this method and no realistic models seems to work for me. Again, one sampler DPM++ SDE Karras seems to adhere to the prompts and BREAK. Sometimes, it is a hit or miss adhering to the prompts too.

Am I doing something wrong, settings, etc. I've spent some time following the usage guideline and examples etc

**Comment by Symbiomatrix** [comment]
It is difficult to determine whether you are doing something incorrectly based on such a vague description, but it is likely. The extension has been tested at different points in time and should work with all samplers and checkpoints, with the exception of ddim and a few others which cannot run with latent mode because they don't support AND.
If you want more specific advice, post examples of your settings and results.
